name: 'Comment a pull request'
inputs:
  comment:
    description: 'The comment to add'
    required: true
  update:
    description: 'Update previous comment'
    required: false
    default: false
  token:
    description: 'GitHub token'
    default: $
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'