name: Comment pr

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Comment PR
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment PR
        uses: ./
        with:
          comment: "An example comment"
          token: ${{ secrets.GITHUB_TOKEN }}